[package]
name = "miragectl"
version.workspace = true
edition.workspace = true

[dependencies]
mirage = { version = "*", path = "../mirage" }

bytes.workspace = true
tokio.workspace = true
clap.workspace = true
eyre.workspace = true
tempfile.workspace = true
figment.workspace = true
serde_json.workspace = true
tokio-util.workspace = true
futures.workspace = true
