[package]
name = "mirage"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { version = "1.11.1", features = ["serde"] }
clap = { version = "4.6.1", features = ["derive"] }
eyre = "0.6.12"
figment = { version = "0.10.19", features = ["tempfile", "toml", "env", "json"] }
glob = "0.3.3"
notify = "8.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tempfile = "3.27.0"
tera = "1.20.1"
tokio = { version = "1.52.3", features = ["signal", "net", "fs", "macros", "tracing", "time", "sync", "rt-multi-thread", "process", "io-util"] }
toml = "1.1.2"
walkdir = "2.5.0"
