[package]
name = "mirage"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
tokio.workspace = true
clap.workspace = true
eyre.workspace = true
figment.workspace = true
glob.workspace = true
notify.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tera.workspace = true
toml.workspace = true
walkdir.workspace = true
